### ISSUE TITLE
2024-04 dataset contains wrong move annotation

### ISSUE THREAD

**Issue by hieuimba** [lichess-org/database#52]
Hi there,
I have found that the Inaccuracy, Mistake, and Blunder annotations are incorrect for the 2024-04 standard-rated data file in the Lichess Database.

Here is an example of a game with evaluation:

[Event "Rated Bullet game"]
[Site "[lichess.org/jHzLmZ8j](https://lichess.org/jHzLmZ8j)"]
[Date "2024.04.03"]
[Round "-"]
[White "Petit_Rock"]
[Black "jctobar"]
[Result "1-0"]
[UTCDate "2024.04.03"]
[UTCTime "19:49:12"]
[WhiteElo "1718"]
[BlackElo "1763"]
[WhiteRatingDiff "+6"]
[BlackRatingDiff "-6"]
[ECO "D00"]
[Opening "Queen's Pawn Game: Levitsky Attack"]
[TimeControl "60+0"]
[Termination "Normal"]

1. d4 { [%eval 0.17] [%clk 0:01:00] } 1... d5 { [%eval 0.25] [%clk 0:01:00] } 2. Bg5 { [%eval -0.26] [%clk 0:01:00] } 2... h6 { [%eval -0.1] [%clk 0:00:56] } 3. Bh4 { [%eval 0.0] [%clk 0:01:00] } 3... c5 { [%eval -0.11] [%clk 0:00:53] } 4. Bg3 { [%eval -0.47] [%clk 0:01:00] } 4... cxd4 { [%eval -0.42] [%clk 0:00:51] } 5. Qxd4?! { [%eval -1.14] [%clk 0:01:00] } 5... Nc6?! { [%eval -1.19] [%clk 0:00:50] } 6. Qd1?! { [%eval -1.39] [%clk 0:00:59] } 6... Nf6?! { [%eval -1.22] [%clk 0:00:48] } 7. Nc3? { [%eval -2.7] [%clk 0:00:58] } 7... e5?! { [%eval -1.97] [%clk 0:00:45] } 8. e3?! { [%eval -1.9] [%clk 0:00:53] } 8... Bb4?! { [%eval -1.37] [%clk 0:00:44] } 9. Bb5?! { [%eval -1.43] [%clk 0:00:51] } 9... O-O?! { [%eval -1.26] [%clk 0:00:42] } 10. a3? { [%eval -2.94] [%clk 0:00:50] } 10... Bxc3+? { [%eval -2.96] [%clk 0:00:40] } 11. bxc3? { [%eval -2.87] [%clk 0:00:50] } 11... Qa5? { [%eval -2.87] [%clk 0:00:37] } 12. Qd3? { [%eval -5.01] [%clk 0:00:43] } 12... e4? { [%eval -5.03] [%clk 0:00:33] } 13. Qd2? { [%eval -5.04] [%clk 0:00:36] } 13... Qxb5? { [%eval -5.28] [%clk 0:00:31] } 14. Ne2? { [%eval -5.13] [%clk 0:00:34] } 14... Na5? { [%eval -5.18] [%clk 0:00:27] } 15. Nd4? { [%eval -5.43] [%clk 0:00:33] } 15... Qd7? { [%eval -5.07] [%clk 0:00:23] } 16. O-O? { [%eval -5.12] [%clk 0:00:32] } 16... Nc4? { [%eval -5.1] [%clk 0:00:22] } 17. Qe2? { [%eval -5.08] [%clk 0:00:30] } 17... Qg4? { [%eval -5.15] [%clk 0:00:19] } 18. Qe1? { [%eval -5.25] [%clk 0:00:27] } 18... Nh5? { [%eval -5.17] [%clk 0:00:17] } 19. h3? { [%eval -5.4] [%clk 0:00:21] } 19... Qg6? { [%eval -5.24] [%clk 0:00:15] } 20. Bh2? { [%eval -6.55] [%clk 0:00:16] } 20... f5? { [%eval -5.17] [%clk 0:00:13] } 21. Ne2? { [%eval -5.53] [%clk 0:00:16] } 21... Nf6? { [%eval -5.13] [%clk 0:00:11] } 22. Bf4? { [%eval -5.25] [%clk 0:00:15] } 22... Qf7? { [%eval -5.41] [%clk 0:00:09] } 23. Bh2? { [%eval -5.41] [%clk 0:00:15] } 23... g5? { [%eval -5.17] [%clk 0:00:08] } 24. Nf4? { [%eval -5.9] [%clk 0:00:15] } 24... gxf4? { [%eval -5.99] [%clk 0:00:07] } 25. Bxf4? { [%eval -6.1] [%clk 0:00:15] } 1-0

The problem starts after the 5.Qxd4 move, which is correctly marked as an inaccuracy. However, all the following moves are marked as inaccuracies where they're not. The same happens after the 10.a3 move, which is a mistake, but all following moves are incorrectly marked as mistakes until the end of the game.

I found this issue in the 2024-04 dataset but I'm not sure if it occurs on any of the older files or not.

**Comment by ornicar** [comment]
Hi, do you mean all annotations are incorrect on all games, or you found some games where it's incorrect?

**Comment by hieuimba** [comment]
Hi there, I tested this out on the 2024-02,03,04, and 05 datasets and it seems like all evaluated games are affected (I didn't do a thorough test though just a few dozen games from the top of each file)

I believe 2024-01 doesn't have this issue from the last time I used it but you might want to check it too just in case

**Comment by ornicar** [comment]
Thanks. I'll look into it.

**Comment by ornicar** [comment]
it will take at least a week to rebuild these 4 months worth of games.

**Comment by hieuimba** [comment]
thanks @ornicar, unfortunately seems like 2024-01 is affected too and I'm not sure how far back this goes

**Comment by ornicar** [comment]
re-indexing 2024-01
