### ISSUE TITLE
stockfish version of evals

### ISSUE THREAD

**Issue by lzanini** [lichess-org/database#53]
Hi, thank you for your work on the lichess database and for the recently added stockfish evaluations. It represents a lot of CPU time and therefore makes for a very valuable dataset.

I believe it would be even more useful if we knew the stockfish version that generated these evals: 100M nodes do not mean the same thing if it was stockfish 16 nnue or stockfish 11 hce.

Is this something you could consider adding in the future ?

**Comment by ornicar** [comment]
Only NNUE evaluations are stored.

https://github.com/lichess-org/lila/blob/master/ui/ceval/src/ctrl.ts#L194
