### ISSUE TITLE
Invalid FENs in 2023-11 dump of Chess 960 games

### ISSUE THREAD

**Issue by jlherren** [lichess-org/database#54]
The file `lichess_db_chess960_rated_2023-11.pgn.zst` contains a whole series of invalid starting FEN positions. For example, the 89569th game contains the follow FEN header:

    [FEN "rkrnnbbq/pppppppp/8/8/8/8/PPPPPPPP/RKRNNBBQ w HEhe - 0 1"]

Chess 960 start positions usually have the castling availability specified as "KQkq" and not using the files where the rooks are, which is odd. But in this case the specification "HEhe" is entirely invalid, because the rooks are on files A and C. On the website that same game (https://lichess.org/osfJ5OM2) shows no castling availability at all in the initial position, which is also wrong.

The file has many other start positions with invalid initial castling availability, some are even just "-".

I didn't find this error in any other files from January 2023 to May 2024 for Chess 960.

**Comment by lenguyenthanh** [comment]
We had a bug around that time: https://github.com/lichess-org/lila/pull/13967.

How should We fix this? Maybe removing those games from database 🤔

**Comment by niklasf** [comment]
So for, for irrecoverable mistakes, we just noted them down under "Known issues".
