### ISSUE TITLE
Missing Volatility Data in Chess Puzzle Dataset

### ISSUE THREAD

**Issue by katoue** [lichess-org/database#56]
In Glicko2, calculating a new player’s rating, rating deviation (RD), and volatility after a match requires all three metrics: rating, RD, and volatility . I've been trying to simulate some new matches with the chess puzzle dataset. The absence of volatility data can led to inaccurate calculations of the new puzzle ratings and RD. I read the lila code only discover the default volatility to be 0.09 and a maximum of 0.1. Is there anyway to access this data?

**Comment by ornicar** [comment]
It didn't seem useful to add `volatility` and I'm still not sure it is, as I don't quite understand why you need it? to "simulate some new matches"?

**Comment by Dboingue** [comment]
It would mean how much the puzzle is being experienced and the puzzle individual rating confidence level. The volatility is just the mechanism by which glicko2 manages the dynamics of the pairing in the pool, and its influence on the rating estiamte confidence, this might provide population scale data anslsysi power for more fine grain questions, also not part of the insufficient open data effort that the unknown date of the puzzle database has left us wanting. For a long time. It seems that the invidual tool premise is dominating the reasoning, from my limited individual point of view, eager to understand what things being what they are, are as they are, and have been for such a while.

The subjective theme votation data.  The ratings.  these are all population based and dynamic.  I am less interest by the contribution of volatility to the per pairing instance change amplitude, and more interested by the uncertainty information it also controls more directly.  A sort of memory of the past level of pool "exposure" over time.

for the dating issue:
https://github.com/lichess-org/database/issues/58#issue-2568780635

**Comment by katoue** [comment]
When you need to determine a puzzle rating for a newly introduced player, such as a bot, you will need volatility to calculate it. 
http://www.glicko.net/glicko/glicko2.pdf

**Comment by katoue** [comment]
> Not sure there is any point in adding this. It's clamped to such a small interval that I doubt it adds any signal about individual puzzles.
> 
> > When you need to determine a puzzle rating for a newly introduced player, such as a bot, you will need volatility to calculate it.
> 
> Yes but then you'd have your own system where you set your own values and let them evolve, no?

That's acceptable but not accurate.

**Comment by katoue** [comment]
Closing as this is no longer needed
