### ISSUE TITLE
[FEATURE REQUEST] Add generation date to puzzle page

### ISSUE THREAD

**Issue by cakiki** [lichess-org/database#58]
It would be useful to add the date the data was last updated since the puzzles file is cumulative.

**Comment by cakiki** [comment]
Happy to send a PR, but I'm not sure when exactly the update was run. Oct 5?

**Comment by Dboingue** [comment]
I don't know if that is what I think it might mean, but I also think that there is some vagueness about what the thing called puzzle database might contain, as it has not date attributed, and any rated thing should be about a traceable pool depedent variable.

And the theme, the ones that are not autotagged or that might change the theme probabilities per human half  pool experience and the data about each puzzle ID player pair expeirence (how confident perhaps its rating might be, its volatiliity to speak glicko).

So it seems like a bunch of floating variables for anyone wanting to do population data analysis.  It looks like another self-centered tool for individuals.  A missed opportunity. But I might be missing a bunch of good reasons.  I wish to be informed then.

So I approve this minimalist issue request.  A date on that page. if not on the database....

**Comment by ornicar** [comment]
> It would be useful to add the date the data was last updated since the puzzles file is cumulative.

I don't understand why it's useful, and what you mean by cumulative?

The puzzle DB is recomputed fully and replaced at the beginning of each month, and sometimes during a month for various reasons.

The static website is computed by https://github.com/lichess-org/database/blob/master/web/index.js

**Comment by cakiki** [comment]
By cumulative I meant that the file is overwritten with every update.

It could be useful for people to know whether and when to update their local file, and for me for example to know when to update the Hugging Face version. (Though for the latter I guess there must be an easier way to figure that out)

**Comment by Dboingue** [comment]
> The puzzle DB is recomputed fully and replaced at the beginning of each month, and sometimes during a month for various reasons.

Is there a trace of that somewhere.  The history of that file? you linked.   It would be nive to make a note of that on the puzzle database page.  and perhaps a changelog.  Does that mean also that the votatoin date is being udpated.  At each update it become a partial snapshot of all the included variables (as the page gives a schema for?).  

And are the prevous databases (and their datestamp) available anywhere?

I am glad to hear that. For the first time.  That the puzzle database is under continuous revision.  But it would be nice to have that historical data nonetheless.  I can,t explain ahead of the research it might allow.. sorry. This is not a cloed questoin with a fintie problem well posed and a a known algorithm that I could give to justify having access to move characterized datasets.

**Comment by ornicar** [comment]
The static website is computed by https://github.com/lichess-org/database/blob/master/web/index.js so the export date can be added there.
